### ISSUE TITLE
skchem package for synergy maps

### ISSUE THREAD

**Issue by ajing** [richlewis42/synergy-maps#1]
Dear synergy maps developers,

I saw the code is using skchem python package. How to install that?

Thanks,
Jing

**Comment by richlewis42** [comment]
Hi Jing,

skchem is an experimental package written by me looking to make rdkit more straightforward to use with pandas and the rest of the scientific python stack.  It should be installable using

`pip install scikit-chem`

Specifically, this package was tested with v0.0.1 release - the skchem API is definitely subject to change, so if it stops working after an update, try `pip install scikit-chem==0.0.1`.  I hope to keep this package up to date with the API though.

The source for scikit-chem is available [here](https://github.com/richlewis42/scikit-chem).

Please let me know if it doesn't work!

**Comment by ajing** [comment]
Could I ask about what dev tools you use for this app? I saw D3, JQuery and AngularJS. I am working on a project with D3. But, I didn't use MVC pattern. So, my current code is hard to maintain. Do you have any suggestion in terms of development?

**Comment by richlewis42** [comment]
My first iteration was the same - VERY hard to maintain and extend.  For this iteration, I used Angular 1 to modularize the app into different web components, which I think I have managed, at least to a certain extent - I feel this is the best way to build an easily maintainable and extendable app.  That said, this attempt is still quite messy as I was new to all the frameworks when I started, so I am planning on a rewrite for the next version.  Also, Angular 2 is coming soon, which seems a more modern way to develop modular apps.  I would recommend looking into a web component library (such as Angular 1 or 2, Aurelia or React) to keep the code separated.

**Comment by ajing** [comment]
Thanks for the suggestion! I am looking at Angular 2. Yes, with growing of functionality, the app becomes too complex to maintain. And, my initial architecture design didn't really anticipate the complexity of current situation. Do you have any response speed problem during your development? I saw the search bar, which might be slow for large data set.

**Comment by ajing** [comment]
Do you use Yeoman also?

**Comment by richlewis42** [comment]
Hi, sorry I have just revisited this thread after a VERY long time (I was replying in the gap between two lectures before, so must have missed your previous reply as the next lecture started).  Thought I would reply anyway, then close it, as I am considering starting version 3 in the near future.

I think you can filter the results in javascript before drawing in the search bar, which would hopefully minimise performance hits.

 I did use yeoman, although I'm not so convinced it is a necessity any more, although can be very nice if you find a good generator, or extend it a bit.
